### ISSUE TITLE
GitHub Pages demo no longer exists

### ISSUE THREAD

**Issue by PButcher** [bryik/aframe-controller-cursor-component#13]
Just noticed that the GitHub Pages branch which powered [the example of this component](https://bryik.github.io/aframe-vive-cursor-component) has disappeared. Can we get it back please? :)

**Comment by bryik** [comment]
Yeah I forgot I was using the /docs folder for ghpages instead of a separate ghpages branch. The latter is more common (it is what the component boilerplate prescribes), but I prefer using "/docs" since the gh pages script never worked for me.

I'll fix this when I have the time. Either I'll go through and change "examples" back to "docs" or create a ghpages branch.

**Comment by bryik** [comment]
I have attempted to fix this. GitHub pages is back up and the examples load in Firefox. 

However, the examples do not load for me in Chrome right now. Hopefully, just a cache issue...
